-- ==============================================================================
-- HCC CHEMAI - SUPABASE DATABASE INITIALIZATION SCHEMA (2026)
-- Project URL: https://xgmwmexfyzgnkcrljdki.supabase.co
-- ==============================================================================

-- 1. BẢNG EXPERIMENTS (Cache phản ứng thí nghiệm, Kế hoạch bài dạy, Đề thi, Dự án STEM)
CREATE TABLE IF NOT EXISTS public.experiments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key TEXT UNIQUE NOT NULL,
    result_json JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. BẢNG USER_PROFILES (Hồ sơ học sinh & giáo viên, EXP, chuỗi học tập, danh hiệu)
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id TEXT PRIMARY KEY,
    email TEXT,
    full_name TEXT,
    role TEXT DEFAULT 'student',
    grade TEXT DEFAULT 'Lớp 10',
    avatar_url TEXT,
    points INTEGER DEFAULT 0,
    streak INTEGER DEFAULT 1,
    nickname TEXT,
    honor_badge TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. BẢNG CHAT_LOGS (Nhật ký tương tác AI Gia sư để giáo viên kiểm duyệt)
CREATE TABLE IF NOT EXISTS public.chat_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    user_query TEXT NOT NULL,
    ai_response TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. BẢNG QUIZ_QUESTIONS (Ngân hàng câu hỏi trắc nghiệm & Đấu trường Kahoot)
CREATE TABLE IF NOT EXISTS public.quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic TEXT,
    question TEXT NOT NULL,
    options JSONB NOT NULL,
    correct_index INTEGER NOT NULL,
    explanation TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. BẢNG ROOMS (Phòng thi đấu Live Kahoot trực tuyến theo mã PIN 6 số)
CREATE TABLE IF NOT EXISTS public.rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_pin TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'waiting', -- 'waiting', 'playing', 'finished'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. BẢNG ROOM_PARTICIPANTS (Danh sách thí sinh tham gia phòng thi Live)
CREATE TABLE IF NOT EXISTS public.room_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_pin TEXT NOT NULL,
    user_name TEXT NOT NULL,
    score INTEGER DEFAULT 0,
    answers JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- BẬT ROW LEVEL SECURITY (RLS) & CẤP QUYỀN TRUY CẬP (ANON & AUTHENTICATED)
-- ==============================================================================

ALTER TABLE public.experiments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_participants ENABLE ROW LEVEL SECURITY;

-- Tạo chính sách cho phép đọc/ghi công khai (Phục vụ học sinh & giáo viên sử dụng Web)
DROP POLICY IF EXISTS "Public access experiments" ON public.experiments;
CREATE POLICY "Public access experiments" ON public.experiments FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access user_profiles" ON public.user_profiles;
CREATE POLICY "Public access user_profiles" ON public.user_profiles FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access chat_logs" ON public.chat_logs;
CREATE POLICY "Public access chat_logs" ON public.chat_logs FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access quiz_questions" ON public.quiz_questions;
CREATE POLICY "Public access quiz_questions" ON public.quiz_questions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access rooms" ON public.rooms;
CREATE POLICY "Public access rooms" ON public.rooms FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access room_participants" ON public.room_participants;
CREATE POLICY "Public access room_participants" ON public.room_participants FOR ALL USING (true) WITH CHECK (true);

-- Bật Realtime cho bảng rooms và room_participants
ALTER PUBLICATION supabase_realtime ADD TABLE public.rooms;
ALTER PUBLICATION supabase_realtime ADD TABLE public.room_participants;
